# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

project 'Runner', {
  'Debug-Etransfer' => :debug,
  'Debug-Ventas' => :debug,
  'Profile-Etransfer' => :release,
  'Profile-Ventas' => :release,
  'Release-Etransfer' => :release,
  'Release-Ventas' => :release,
}

target 'Etransfer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Etransfer

  target 'EtransferTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Ventas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ventas

  target 'VentasTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
